<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BGHMBCP0734" failures="1" tests="12" name="com.testenv.test.AssignmentTask" time="130.243" errors="0" timestamp="19 Aug 2021 14:27:05 GMT" skipped="0">
  <testcase classname="com.testenv.test.AssignmentTask" name="test11" time="13.094"/>
  <testcase classname="com.testenv.test.AssignmentTask" name="test12" time="10.007">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at com.testenv.test.AssignmentTask.test12(AssignmentTask.java:122)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test12 -->
  <testcase classname="com.testenv.test.AssignmentTask" name="test1" time="11.111"/>
  <testcase classname="com.testenv.test.AssignmentTask" name="test5" time="14.361"/>
  <testcase classname="com.testenv.test.AssignmentTask" name="test6" time="12.759"/>
  <testcase classname="com.testenv.test.AssignmentTask" name="test8" time="9.272"/>
  <testcase classname="com.testenv.test.AssignmentTask" name="test10" time="8.929"/>
  <testcase classname="com.testenv.test.AssignmentTask" name="test2" time="12.219"/>
  <testcase classname="com.testenv.test.AssignmentTask" name="test4" time="13.638"/>
  <testcase classname="com.testenv.test.AssignmentTask" name="test7" time="8.320"/>
  <testcase classname="com.testenv.test.AssignmentTask" name="test9" time="8.229"/>
  <testcase classname="com.testenv.test.AssignmentTask" name="test3" time="8.304"/>
</testsuite> <!-- com.testenv.test.AssignmentTask -->
